<?php

return [
    [
        'name' => 'key',
        'title' => '应用key',
        'type' => 'string',
        'content' => [],
        'value' => 'LTAI4G43tU2urpGh8ZpXxNjL',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'secret',
        'title' => '密钥secret',
        'type' => 'string',
        'content' => [],
        'value' => 'h2suBTvRwNzQG6stdWh2b0ffAaIVJy',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sign',
        'title' => '签名',
        'type' => 'string',
        'content' => [],
        'value' => 'ABC商城',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'template',
        'title' => '短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => 'SMS_205900012',
            'resetpwd' => 'SMS_205900011',
            'changepwd' => 'SMS_114000000',
            'changemobile' => 'SMS_114000000',
            'profile' => 'SMS_114000000',
            'notice' => 'SMS_114000000',
            'mobilelogin' => 'SMS_205900014',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '应用key和密钥你可以通过 https://ak-console.aliyun.com/?spm=a2c4g.11186623.2.13.fd315777PX3tjy#/accesskey 获取',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
